name: Build Main Branch

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml

  build-android:
    uses: ./.github/workflows/reusable-build-mobile.yml
    with:
      platform: android

  build-ios:
    uses: ./.github/workflows/reusable-build-mobile.yml
    with:
      platform: ios

  lint-and-typecheck:
    uses: ./.github/workflows/reusable-lint-typecheck.yml

  deploy-android:
    needs: [test, build-android, build-ios, lint-and-typecheck]
    uses: ./.github/workflows/reusable-deploy-android.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

  deploy-ios:
    needs: [test, build-android, build-ios, lint-and-typecheck]
    uses: ./.github/workflows/reusable-deploy-ios.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
