name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml

  build-android:
    uses: ./.github/workflows/reusable-build-mobile.yml
    with:
      platform: android

  build-ios:
    uses: ./.github/workflows/reusable-build-mobile.yml
    with:
      platform: ios

  lint-and-typecheck:
    uses: ./.github/workflows/reusable-lint-typecheck.yml
