name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  build-android:
    uses: ./.github/workflows/build-mobile.yml
    with:
      platform: android
      run-tests: true

  build-ios:
    uses: ./.github/workflows/build-mobile.yml
    with:
      platform: ios
      run-tests: false

  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Check Expo configuration
        run: npx expo doctor
