name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  build-android:
    uses: ./.github/workflows/common/build-mobile.yml
    with:
      platform: android
      run-tests: true

  build-ios:
    uses: ./.github/workflows/common/build-mobile.yml
    with:
      platform: ios
      run-tests: false

  lint-and-typecheck:
    uses: ./.github/workflows/common/lint-typecheck.yml
